# Generated by Django 2.1.4 on 2019-01-13 11:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('source_link', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencies', models.TextField()),
                ('governor', models.TextField()),
                ('dependent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('lemma', models.TextField()),
                ('char_begin', models.IntegerField()),
                ('char_end', models.IntegerField()),
                ('POS', models.TextField()),
                ('NER', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('released_date', models.DateField()),
                ('difficulty', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('xml', models.TextField()),
                ('source_link', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentences', to='lango_content.Article')),
            ],
        ),
        migrations.AddField(
            model_name='pos',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='lango_content.Sentence'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency', to='lango_content.Sentence'),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='articles', to='lango_content.Category'),
        ),
    ]
