# Generated by Django 2.1.4 on 2019-01-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lango_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PatternCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pattern_category', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatternType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pattern',
            name='Pattern_Category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lango_content.PatternCategory'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='Pattern_Type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lango_content.PatternType'),
        ),
    ]
