# Generated by Django 2.1.4 on 2019-01-16 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lango_content', '0002_auto_20190116_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='Pattern_Type_id',
        ),
        migrations.AddField(
            model_name='pattern',
            name='pattern_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patterntag', to='lango_content.PatternType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pattern',
            name='Pattern_Category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorytag', to='lango_content.PatternCategory'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
