# Generated by Django 2.1.4 on 2019-01-16 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lango_content', '0003_auto_20190116_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='pattern_Type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patterntag', to='lango_content.PatternType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pattern',
            name='pattern_name',
            field=models.CharField(max_length=100),
        ),
    ]
