# Generated by Django 2.1.4 on 2019-01-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lango_content', '0005_sentence_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='pattern',
        ),
        migrations.AddField(
            model_name='sentence',
            name='pattern',
            field=models.ManyToManyField(related_name='pattern_tag', to='lango_content.Pattern'),
        ),
    ]
