# Generated by Django 2.1.4 on 2019-01-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lango_content', '0007_auto_20190116_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='pattern',
            field=models.ManyToManyField(related_name='pattern_tag', to='lango_content.Pattern'),
        ),
    ]
