# Generated by Django 2.1.4 on 2019-01-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lango_content', '0008_auto_20190116_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='pattern',
            field=models.ManyToManyField(blank=True, null=True, to='lango_content.Pattern'),
        ),
    ]
